import { useQueryClient } from "@tanstack/react-query";
import { useSession } from "next-auth/react";
import Leftbar from "../components/Leftbar";
import Rightbar from "../components/Rightbar";
import { Tweet } from "../components/Timeline";
import { trpc } from "../utils/trpc";
import Head from "next/head";

export default function Liked() {
  const { data: session } = useSession();

  const { data } = trpc.user.getLikes.useQuery({
    id: session?.user?.id,
  });
  const client = useQueryClient();

  console.log(data);
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen justify-center">
        <Leftbar />

        <div>This is still Work in Progress, please come back later :) </div>
        <Rightbar />
      </div>
    </>
  );
}
